languageName = "English"
weight = 1
title = "Zakk"

[params.author]
  name = "Zakk"
  image = "profile.jpg"
  headline = " Australia 路  Guinea pigs 路  Gaming"
  bio = "Linux 路 Finance 路 Longdistance love ┓┑<br/>Ambient 路 Design 路 Cozy life"
  links = [
    { instagram = "https://www.instagram.com/zakk.au/" },
    { github = "https://github.com/Zakkaus" },
    { x = "https://x.com/zakkauu" },
    { email = "mailto:admin@zakk.au" }
  ]
