languageName = "æ¼¢èª"
languageCode = "zh-Hant"
weight = 2
title = "Zakk"

[params.author]
  name = "Zakk"
  image = "profile.jpg"
  headline = "ğŸ“ æ¾³æ´² Â· ğŸ¹ å¤©ç«ºé¼  Â· ğŸ® éŠæˆ²"
  bio = "Linux Â· é‡‘è Â· ç•°åœ°ä¼´ä¾¶ ğŸ©·ğŸ’›ğŸ©µ<br/>æ°›åœéŸ³æ¨‚ Â· è¨­è¨ˆ Â· å±…å®¶ç”Ÿæ´»"
  links = [
    { instagram = "https://www.instagram.com/zakk.au/" },
    { github = "https://github.com/Zakkaus" },
    { x = "https://x.com/zakkauu" },
    { email = "mailto:admin@zakk.au" }
  ]
