languageName = "æ¼¢èª"
languageCode = "zh-Hant"
weight = 2
title = "Zakk"

[params.author]
  name = "Zakk"
  image = "profile.jpg"
  headline = "æ¾³æ´² Â· ç™‚ç™’æ°›åœ Â· è¨­è¨ˆ Â· å¤©ç«ºé¼ "
  bio = "éŠæˆ² Â· Linux Â· é‡‘è Â· ç•°åœ°ä¼´ä¾¶ Â· ğŸ©·ğŸ’›ğŸ©µ"
  links = [
    { instagram = "https://www.instagram.com/zakk.au/" },
    { github = "https://github.com/Zakkaus" },
    { x = "https://x.com/zakkauu" },
    { email = "mailto:admin@zakk.au" }
  ]
